---
- hosts: localhost
  tasks:
    - name: Create pritunl client container.
      docker_container:
        name: pritunl-client-base
        image: centos:7
        command: /bin/bash
        tty: yes
        state: started

- hosts: pritunl-client-base
  connection: docker
  roles:
    - role: shomatan.pritunl-client
  tasks:
    - name: Copy docker entrypoint script.
      template:
        src: docker-entrypoint.sh.j2
        dest: /docker-entrypoint.sh
        mode: 0755
